### ISSUE TITLE
Serviio Tubefox doesn't detect YT plugin when other plugins are installed

### ISSUE THREAD

**Issue by Boncurek84** [sorinello/serviio-tubefox#1]
I have Serviio 1.6 installed on my PC (Windows 10), I put the YT plugin from serviio.org forum into Plugins directory however the Serviio-tubefox doesn't starts. The YT icon is red and says YT Plugin not found.  My Firefox version is 45.0.1. How to solve that problem.

**Comment by sorinello** [comment]
You did not install the Serviio Youtube plugin. See http://forum.serviio.org/viewtopic.php?f=20&t=3276 and search for the Groovy attachment. You need to put that groovy file in your Serviio plugins dir and restart Serviio. if you don't do this, Serviio doesn't know how to read Youtube URL's.

**Comment by Boncurek84** [comment]
I have already rebooted Servio for 5 times. I dowloaded the plugin from
 that thread. So you don't know what is wrong exactly.

**Comment by Boncurek84** [comment]
Could you tell me how to restart serviio. I think stop and start server again.

**Comment by sorinello** [comment]
Go to Windows Services and restart the Serviio Service. Or more simply, reboot your computer. Also, are you using other Serviio plugins besides the Youtube one ?

**Comment by Boncurek84** [comment]
I did everything what you'd told me. The problem is stil active.
I have a Vimeo plugin too.

**Comment by sorinello** [comment]
@Boncurek84 ok, after I installed the Vimeo plugin also, I get the same message. I have reproduced the problem, and working on a fix.

**Comment by Boncurek84** [comment]
I think that problem is fixed when you use only YT plugin.
I deleted  both plugins then reinstalled YT plugin and rebooted Serviio services. (services.msc) 
Finally it works.  Thanks for your great support.

**Comment by sorinello** [comment]
@Boncurek84 Indeed, that is the problem. I have already submitted a new version to Mozilla Addons which fixes the problem. Very soon, the problem will be fixed (you will have to upgrade to the newer version of the serviio-tubefox) and you will be able to use both plugins.

**Comment by sorinello** [comment]
@Boncurek84 the new serviio-tubefox is available (version 0.0.2). Can you please update the extension, put both youtube and vimeo plugins and see if it works now with both plugins installed ? Thanks in advance !
